version: '3'
services:
  example-nestjs-service:
    build:
      context: ./example-nestjs-service/
      dockerfile: ./docker/development.Dockerfile
    ports:
      - "${EXAMPLE_NESTJS_SERVICE_DEBUG_PORT:-9229}:9229"
      - "${EXAMPLE_NESTJS_SERVICE_HTTP_PORT:-80}:3000"
    volumes:
      - './example-nestjs-service/src:/app/src'
      - './example-nestjs-service/src/views:/app/dist/views'
    networks:
      - red_network
    dns:
      - 9.9.9.9
      - 8.8.8.8
volumes:
  example-nestjs-service:
    driver: local
networks:
  red_network:
