version: '3'
services:
  example-nestjs-service:
    build:
      context: ./example-nestjs-service/
      dockerfile: ./docker/production.Dockerfile
    ports:
      - "${EXAMPLE_NESTJS_SERVICE_HTTP_PORT:-80}:3000"
    networks:
      - red_network
    dns:
      - 9.9.9.9
      - 8.8.8.8
    restart: always  
networks:
  red_network:
    